export enum CommandType {
  Dynamic = 'extension.addFlutter2_Dynamic',
  AsoDev = 'extension.addFlutterAsoDev',
  BigPack = 'extension.addFlutter2BigPack',
  SmallPack = 'extension.addFlutter2SmallPack',
  Bloc = 'extension.addFlutter2Bloc',
  State = 'extension.addFlutter2State',
  Event = 'extension.addFlutter2Event',
  Model = 'extension.addFlutter2Model',
  Page = 'extension.addFlutter2Page',
  Provider = 'extension.addFlutter2Provider',
  Repository = 'extension.addFlutter2Repository',
  Screen = 'extension.addFlutter2Screen',
  Templates = 'extension.addFlutter2zTemplates',
  Index = 'extension.addFlutter2zIndex',
}
