export enum ResourceType {
  Dynamic = 'dynamic',
  BigPack = 'bigpack',
  SmallPack = 'smallpack',
  Bloc = 'bloc',
  Event = 'event',
  Model = 'model',
  Page = 'page',
  Provider = 'provider',
  Repository = 'repository',
  Screen = 'screen',
  State = 'state',
  Index = 'index',
  Templates = 'Templates',
}
